apiVersion: batch/v1
kind: CronJob
metadata:
  name: health-check-cronjob
spec:
  schedule: "*/1 * * * *" # Every 1 minutes  
  concurrencyPolicy: Forbid          # avoid overlapping jobs
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: health-check
              image: curlimages/curl:latest
              command: [ "sh", "-c" ]
              #minikube service devops-k8s-phase2-service --url
              args:              
                - |
                - SERVICE_URL=$(minikube service devops-k8s-phase2-service --url)
                  if curl -s --fail ${SERVICE_URL}/health2; then
                    RESULT="SUCCESS"
                  else
                    RESULT="FAILURE"
                  fi
                - echo "${SERVICE_URL}" >> /data/health-check.log
                - echo "$TIMESTAMP - Health Check ${RESULT}" >> /data/health-check.log
#                - date '+%Y-%m-%d %H:%M:%S %Z' >> /data/health-check.log
              volumeMounts:
                - name: health-volume
                  mountPath: /data
            - name: html-generator
              image: busybox
              command:
                - /bin/sh
                - -c
                - |
                  echo "<html><head><title>Health Check</title></head><body><h1>Health Check Results</h1><div class="topnav"><a class="active" href="/">Home</a><a href="/health">Health</a><a href="/ready">Ready</a><a href="/api/data">API</a><a href="/images">Images</a><a href="/health2">Health2</a><a href="/about">About</a></div><pre>" > /var/log/health.html
                  cat /var/log/health-check.log >> /var/log/health.html
                  echo "</pre></body></html>" >> /var/log/health.html
              volumeMounts:
                - name: health-volume
                  mountPath: /var/log
          restartPolicy: OnFailure
          volumes:
            - name: health-volume
              persistentVolumeClaim:
                claimName: health-check-pvc
