apiVersion: batch/v1
kind: CronJob
metadata:
  name: health-check-cronjob
spec:
  schedule: "*/1 * * * *" # Every 1 minutes  
  concurrencyPolicy: Forbid          # avoid overlapping jobs
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: health-check
              image: curlimages/curl:latest
              command: ["/bin/sh", "-c"]
              args:
                - |
                  set -eu

                  # Use cluster DNS, not minikube CLI
                  SERVICE_HOST="devops-k8s-phase2-service"
                  SERVICE_PORT="5008"
                  HEALTH_PATH="/health2"
                  SERVICE_URL="http://${SERVICE_HOST}:${SERVICE_PORT}${HEALTH_PATH}"

                  TIMESTAMP="$(date '+%Y-%m-%d %H:%M:%S %Z')"

                  if curl -sS -m 10 --fail "${SERVICE_URL}"; then
                    RESULT="SUCCESS"
                  else
                    RESULT="FAILURE"
                  fi

                  {
                    echo "SERVICE_URL=${SERVICE_URL}"
                    echo "${TIMESTAMP} - Health Check ${RESULT}"
                    echo "----------------------------------------"
                  } >> /data/health-check.log
              volumeMounts:
                - name: health-volume
                  mountPath: /data

            - name: html-generator
              image: busybox
              command:
                - /bin/sh
                - -c
                - |                  
                  echo "<html><head><title>Health Check</title><style>a{margin-right: 3px;}</style></head><body><div class="topnav" style:"margin-right: 10px"><a class="active" href="/">Home </a><a href="/health">Health</a><a href="/ready">Ready</a><a href="/api/data">API</a><a href="/images">Images</a><a href="/health2">Health2</a><a href="/about">About</a></div><h1>Health Check Results</h1><pre>" > /var/log/health.html
                  cat /var/log/health-check.log >> /var/log/health.html
                  echo "</pre></body></html>" >> /var/log/health.html
              volumeMounts:
                - name: health-volume
                  mountPath: /var/log
          restartPolicy: OnFailure
          volumes:
            - name: health-volume
              persistentVolumeClaim:
                claimName: health-check-pvc
