
apiVersion: batch/v1
kind: CronJob
metadata:
  name: health-check-cronjob
spec:
  schedule: "*/5 * * * *" # Every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: health-check
              image: curlimages/curl:latest
              command:
                - /bin/sh
                - -c
                - |
                  TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
                  if curl -s --fail http://127.0.0.1:5008/health2; then
                    RESULT="SUCCESS"
                  else
                    RESULT="FAILURE"
                  fi
                  echo "$TIMESTAMP - Health Check: $RESULT" >> /var/log/health-check.log
              volumeMounts:
                - name: health-volume
                  mountPath: /var/log
            - name: html-generator
              image: busybox
              command:
                - /bin/sh
                - -c
                - |
                  echo "<html><head><title>Health Check</title></head><body><h1>Health Check Results</h1><pre>" > /var/log/health.html
                  cat /var/log/health-check.log >> /var/log/health.html
                  echo "</pre></body></html>" >> /var/log/health.html
              volumeMounts:
                - name: health-volume
                  mountPath: /var/log
          restartPolicy: OnFailure
          volumes:
            - name: health-volume
              persistentVolumeClaim:
                claimName: health-check-pvc
