apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: devops-k8s-phase2-service
  namespace: devops-phase2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
