# HPA
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: devops-k8s-phase2-service
#  namespace: devops-phase2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devops-k8s-phase2
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50