#PV and PVC definition
# Persistent Volume Definition
apiVersion: v1
kind: PersistentVolume
metadata:
  name: health-check-pv
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/
---
# Persistent Volume Claim Definition
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: health-check-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  storageClassName: standard
